services:
  pico-cpp-sdk:
    image: pico-cpp-sdk
    privileged: true
    build: ./docker
    env_file: .env
    volumes:
      - type: bind
        source: ./
        target: /opt/code/green-pi
      - type: bind
        source: /dev/bus/usb
        target: /dev/bus/usb
