services:
  build:
    image: pico-cpp-sdk
    privileged: true
    build: ./docker
    env_file: .env
    volumes:
      - type: bind
        source: ./
        target: /opt/code/green-pi
      - type: volume
        source: vscode-server
        target: /opt/code/.vscode-server
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/ttyACM10:/dev/ttyACM10
volumes:
  vscode-server:
